name: CI - gemmtr BLAS

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libopenblas-dev g++

    - name: Build
      run: |
        cd gemmtr_BLAS
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -v

    - name: Run interface tests
      run: cd gemmtr_BLAS/build && ./test

    - name: Run performance tests
      run: cd gemmtr_BLAS/build && ./benchmark